project:
  type: website
  output-dir: docs

website:
  title: "Week 2 Website - Sean Murphy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: shelter.qmd
        text: Occupancy
      - href: toronto.qmd
        text: Toronto Data
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



